pipeline {
    agent any
    stages {
        stage('Test'){
            steps {
                sh 'docker build -f docker/test-dockerfile-v1 -t chat-test .'
                sh 'docker run chat-test'

            }
        }
    }
}